######################################################################
# Automatically generated by qmake (2.01a) ?? ?? 30 14:06:18 2010
######################################################################

CONFIG +=debug
TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .
QT += network
FORMS += mainwindow.ui

# Input
HEADERS += verycd.h mainwindow.h
SOURCES += main.cpp verycd.cpp mainwindow.cpp
