www.verycd.com
/sto/book/page%1
<li>(?:.*)<a href=(?:.*)<img load-src=\"(.*/thumb.jpg)\" (?:.*)\[(.*)\](?:.*)<a href=\"(.*)\" onclick(?:.*)+this.href\);\" >(.*)</a>\s*<img alt=\"精华资源\"(?:.*)'/stat/indexUsername/'\);\">(.*)</a></p>(?:.*)(?:地区\(语言\):(\S+))?\s*(?:发行时间:(\S+)\s*<br />)?\s*(.*)<a href(?:.*)<span class=\"date-time\">(.*)</span> 发布, <span class=\"date-time\">(.*)</span> 更新 - <strong>(.*)</strong>个文件, <strong>(.*)</strong>, (?:<strong>(.*)</strong>条评论|暂无评论)</span>
class=\"forminput\" name=(?:.*) value=\"(.*)\"(?:.*)onclick=\"(?:.*)\" checked=\"checked\"(?:.*)><a href=\"(.*)\"(?:.*)ed2k=\"(?:.*)\">(.*)</a>(?:.*)<a(?:.*)</a>(?:.*)<td(?:.*)>(.*)</td>
