######################################################################
# Automatically generated by qmake (2.01a) ?? ?? 30 14:06:18 2010
######################################################################

CONFIG +=debug
TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .
QT += network

# Input
HEADERS += verycd.h
SOURCES += main.cpp verycd.cpp
