######################################################################
# Automatically generated by qmake (2.01a) Wed Mar 9 15:39:22 2011
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .
QT += network xml

# Input
HEADERS += extractor.h
SOURCES += extractor.cpp main.cpp
